name: Multi-branch Compatibility

on:
    pull_request:
        branches: [main]

jobs:
    cherry_pick_develop19:
        env:
            HEAD_REF: ${{ github.ref }}
            HEAD_SHA: ${{ github.event.pull_request.head.sha }}
            COMMITS: ${{ github.event.pull_request.commits }}
            COMPARE_REF: develop/1.9
        name: develop/1.9
        runs-on: ubuntu-latest
        steps:
            - run: |
                  echo "FETCH_DEPTH=$(( $COMMITS + 1 ))" >> $GITHUB_ENV
            - uses: actions/checkout@v2
              with:
                  ref: ${{ env.HEAD_SHA }}
                  fetch-depth: ${{ env.FETCH_DEPTH }}
            - run: |
                  git branch head_branch $HEAD_SHA
                  git fetch --no-tags --depth=1 origin $COMPARE_REF
                  git checkout -b $COMPARE_REF origin/$COMPARE_REF
            - name: "cherry-pick test"
              run: |
                  START_PARENT_SHA=$( git rev-parse $HEAD_SHA~$COMMITS )
                  RANGE=$START_PARENT_SHA..$HEAD_SHA

                  echo "cherry-pick $RANGE"
                  git cherry-pick --no-commit $RANGE &> /dev/null || TRUE
                  echo
                  git diff --check && echo "No conflicts detected" || TRUE

            - name: "Cleanup"
              run: |
                  git cherry-pick --abort || TRUE
