name: Composer

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - name: Install Composer Dependencies
        run: |
          cd ../..
          composer install --prefer-dist
