name: Run composer

on: [push, pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      name: Run composer
      uses: nick-zh/composer-php@master
      with:
        action: 'install -oa'
